theme = "mainroad"
baseURL = "https://ericliu03.github.io/"
languageCode = "en-us"
title = "Yang's Blog"
rssLimit = 5
paginate = "5" # Number of posts per page
pygmentsCodeFences = true

googleAnalytics = "UA-138995517-1"
disqusShortname = "ericliu03-blog"

[Author] # Used in authorbox
  name = "Eric"
  bio = "Software Engineer, with interests in algorithm"
  avatar = "img/avatar1.png"


[Params]
  subtitle = "About Algorithms" # Subtitle of your site. Used in site header
  description = "Eric's Personal blog about tech" # Site description. Used in meta description
  #copyright = "Yang Liu" # copyright holder, otherwise will use site title

  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  #mainSections = ["post", "blog", "news"] # specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  customCSS = ["css/custom.css"] # Include custom CSS files


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  # github = "username"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"
